apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: service-mesh-demo
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: quay.io/reselbob/service-mesh-payments:v1.0
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
   namespace: service-mesh-demo
  name: recommendations-food
  labels:
    app: recommendations
    version: food
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendations
      version: food
  template:
    metadata:
      labels:
        app: recommendations
        version: food
    spec:
      containers:
      - name: recommendations-food
        image: quay.io/reselbob/service-mesh-recommendations:v1.0
        env:
          - name: RECOMMENDATION_CATEGORY
            value: "FOOD"
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations-music
  namespace: service-mesh-demo
  labels:
    app: recommendations
    version: food
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendations
      version: music
  template:
    metadata:
      labels:
        app: recommendations
        version: music
    spec:
      containers:
      - name: recommendations-music
        image: quay.io/reselbob/service-mesh-recommendations:v1.0
        env:
          - name: RECOMMENDATION_CATEGORY
            value: "MUSIC"
        ports:
        - containerPort: 8080
