apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: service-mesh-demo
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: quay.io/reselbob/service-mesh-orders:v1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: PAYMENTS_URL
          value: "http://payments:8080"
        - name: RECOMMENDATIONS_URL
          value: "http://recommendations:8080"
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: service-mesh-demo
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: tcp-api
      
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: orders
  namespace: service-mesh-demo
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: orders
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
