apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: service-mesh-demo
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: quay.io/reselbob/service-mesh-payments:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: service-mesh-demo
spec:
  selector:
    app: payments
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: tcp-api
