apiVersion: v1
kind: Service
metadata:
  name: recommendations
  namespace: service-mesh-demo
spec:
  selector:
    app: recommendations
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
