##################################################################################################
# Orders services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    app: orders
    service: orders
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: orders
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-mesh-demo-orders
  labels:
    account: orders
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: orders
    spec:
      serviceAccountName: service-mesh-demo-orders
      containers:
      - name: orders
        image: quay.io/reselbob/service-mesh-orders:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
##################################################################################################
# Payments services
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    app: payments
    service: payments
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: payments
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-mesh-demo-payments
  labels:
    account: payments
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: payments
        version: v1
    spec:
      serviceAccountName: service-mesh-demo-payments
      containers:
      - name: payments
        image: quay.io/reselbob/service-mesh-payments:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
##################################################################################################
# Recommendations
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: recommendations
  labels:
    app: recommendations
    service: recommendations
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: recommendations
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-mesh-demo-recommendations
  labels:
    account: recommendations
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations-food
  labels:
    app: recommendations
    version: food
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendations
      version: food
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: recommendations
        version: food
    spec:
      serviceAccountName: service-mesh-demo-recommendations
      containers:
      - name: reviews
        image: quay.io/reselbob/service-mesh-recommendations:v1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: RECOMMENDATION_CATEGORY
          value: "FOOD"
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations-music
  labels:
    app: recommendations
    version: music
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendations
      version: music
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: recommendations
        version: music
    spec:
      serviceAccountName: service-mesh-demo-recommendations
      containers:
      - name: reviews
        image: quay.io/reselbob/service-mesh-recommendations:v1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: RECOMMENDATION_CATEGORY
          value: "MUSIC"
        ports:
        - containerPort: 8080
---
