apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-service-food
  namespace: service-mesh-demo
spec:
  hosts:
  - recommendations
  http:
    - route:
      - destination:                    ##############################################
          host: recommendations         # The K8S recommendations service, in addition
          subset: recommendation-food   # to using the labels declared in its
          Port:                         # spec.selector attribute, will bind to pods 
            number: 8080                # that also have labels defined in the
        weight: 100                     # recommendation-food subset of the Destination
                                        # Rule.
                                        ##############################################
